name: FirstTest

on:
  branches: [ init ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
      steps:
      -uses: action/checkout@v2
      -run : g++ -std=c++17 *.cpp
      -run : ./teszt.bash
      -run : diff outputs.txt results.txt 
