name: FirstTest

on:
  push:
    branches: [ init ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -run : g++ -std=c++17 *.cpp
      -run : ./teszt.bash
      -run : diff outputs.txt results.txt 
