FROM ubuntu:20.04

RUN apt-get update && apt-get install --no-install-recommends -y \
  g++ \
  g++-10 \
  make \
  cppcheck \
  valgrind \
  clang \
  graphviz \
  doxygen \
  libgtest-dev \
  cmake \
  git \
&& rm -rf /var/lib/apt/lists/*