name: Doxygen Test

on:
  push:
    branches: 
      - docker
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: mzsolt97/mosze
    
    steps:
      - uses: actions/checkout@v2
      - run: doxygen doxconf
        
      - name: Push git subdirectory as branch
        uses: s0/git-publish-subdir-action@v2.4.0

        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: DOCS
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
