name: Makefile

on:
  push:
    branches: [ makefile ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -std=c++17 *.cpp
      - run: bash ./teszt.bash
      - run: diff outputs.txt results.txt
      - run: sudo apt install clang
      - run: make game
      - run: clang++ *.cpp -Wall
      - run: sudo apt install cppcheck
      - run: cppcheck *.cpp --enable=warning
      - run: clang++ *.cpp -fsanitize=address
      - run: clang++ *.cpp -fsanitize=memory
      - run: cppcheck *.cpp --enable=warning,style,performance --output-file=style_performance1.txt
      - name: Upload file
        uses: actions/upload-artifact@v2
        with:
          name: style_performance1
          path: style_performance1.txt

          
