name: FirstTest

on:
  push:
    branches: [ init ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -std=c++17 *.cpp
      - run: bash ./teszt.bash
      - run: diff outputs.txt results.txt
      - run: sudo apt install clang
      - run: g++ *.cpp -Wall
      - run:  g++ *.cpp -Wextra
      - run: clang++ *.cpp -Wall
      - run: sudo apt install cppcheck
      - run: cppcheck *.cpp --enable=warning
      - run: clang++ *.cpp -fsanitize=address
      - run: clang++ *.cpp -fsanitize=memory
          
