name: FirstTest

on:
  push:
    branches: [ init ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -std=c++17 *.cpp
      - run: bash ./teszt.bash
      - run: diff outputs.txt results.txt
      - run: sudo apt install clang
      - run: g++ *.cpp -Wall
      - run:  g++ *.cpp -Wextra
      - run: clang++ *.cpp -Wall
      - run: sudo apt install cppcheck
      - run: cppcheck *.cpp --enable=warning
      - run: clang++ *.cpp -fsanitize=address
      - run: clang++ *.cpp -fsanitize=memory
      - run: sudo apt install valgrind
      - run: valgrind --leak-check=yes --log-file=valgrind.log --error-exitcode=1 -v ./a.out units/Alduin.txt units/Sally.txt
      - run: valgrind --tool=callgrind --log-file=valcallgrind.log ./a.out units/Alduin.txt units/Sally.txt
      - name: Uploading valgrind results
        uses: actions/upload-artifact@v2
        with:
          name: valgrind
          path: ./valgrind.txt

      - name: Uploading callgrind results
        uses: actions/upload-artifact@v2
        with:
           name: valcallgrind
           path: ./valcallgrind.txt
          
