name: Attackspeed Workflow

on:
  push:
    branches: [ attackspeed ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -std=c++17 *.cpp
      - run: bash ./teszt.bash
      - run: diff outputs.txt results.txt
          
