name: RefactorTest

on:
  push:
    branches: [ docker ]



jobs:
  build:
    runs-on: ubuntu-latest
    container: mzsolt97/mosze
    steps:
      - uses: actions/checkout@v2
      - run: make game
      - run: cppcheck *.cpp --enable=warning
      - run: cppcheck *.cpp --enable=warning,style,performance --output-file=style_performance1.txt
      - run: valgrind --leak-check=full --error-exitcode=1 ./game scenario1.json
      - run: make clean
      - name: Upload file
        uses: actions/upload-artifact@v2
        with:
          name: style_performance1
          path: style_performance1.txt


          
