name: FirstTest

on:
  push:
    branches: [ init ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -Wall *.cpp
      - run: ./teszt.bash
      - run: diff outputs.txt results.txt
          
