name: Google tests
on:
    push:
        branches: [docker]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: mzsolt97/mosze
    steps:
      - uses: actions/checkout@v2
      - run: cd units && cmake CMakeLists.txt && make && ./googleTests
