name: Google tests
on:
    push:
        branches: [docker]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: mzsolt97/mosze
    steps:
      - uses: actions/checkout@v2
      - run: cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
      - run: cd units && cmake CMakeLists.txt && make && ./googleTests
